### ISSUE TITLE
Lumen Worker and WorkerCommand broken on lumen 6

### ISSUE THREAD

**Issue by itsursujit** [laravel/lumen-framework#1005]
- Lumen Version: 6.2
- PHP Version: 7.3
- Database Driver & Version:

### Description:
```
bootstap/app.php

$app->singleton(App\Webhooks\WebhookWorker::class, function ($app) {
   // Custom Worker
    return new App\Webhooks\WebhookWorker(
        $app['queue'], $app['events'], $app[Illuminate\Contracts\Debug\ExceptionHandler::class]
    );
});

Error: Required field $isDownForMaintenance is missing
```

After I added a dummy function and defined it as 4th param in above, I received another error:

>  Too few arguments to function Illuminate\Queue\Console\WorkCommand::__construct(), 1 passed in /Users/sujit/Sites/smsto/api/app/Console/Commands/CustomWorkCommand.php on line 45 and exactly 2 expected

CustomWorkCommand.php __construct:

```
public function __construct(WebhookWorker $worker)
    {
        parent::__construct($worker);
    }
```

Above code was working on Lumen 5.8 but when I upgraded to lumen 6.2, 

### Steps To Reproduce:
1. Add custom worker and worker command on lumen . 5.8
2. Upgrade lumen 6.2
3. Run custom worker command

**Comment by driesvints** [comment]
The `Worker` class got an extra dependency in https://github.com/laravel/framework/pull/29224
