### ISSUE TITLE
artisan commands

### ISSUE THREAD

**Issue by lobin21** [laravel/lumen-framework#969]
After upgrading from v5.8.35 to v6 artisan commands are no longer working and giving an error.

Command run: `php artisan list` (any artisan command fails)
Output:
`Too few arguments to function Illuminate\Queue\Console\RestartCommand::__construct(), 0 passed in /Users/Jakub/Development/work/OMG/hex-api/vendor/laravel/lumen-framework/src/Console/ConsoleServiceProvider.php on line 307 and exactly 1 expected`

I have also tried on fresh lumen project after running: `lumen new AppName` and have the same results. Artisan commands are not working

I have downgraded back to v5.8 and all is working again.

Thanks!

**Comment by zhouzishu** [comment]
https://github.com/laravel/lumen-framework/issues/966

**Comment by lobin21** [comment]
That was quick!!! Great thanks!

**Comment by lobin21** [comment]
I'm still getting this error with version 6.0.1!!

**Comment by zhouzishu** [comment]
Me too. I know that there is a PR to fix it, but after I updated to 6.0.1, this file is not changed.

https://github.com/laravel/lumen-framework/pull/968/commits/ae4bd9ff786344c278b463a7428301e879f7aac1

**Comment by driesvints** [comment]
Some changes from the pr were reverted right before merging apparently. Released v6.0.2 which should fix things

**Comment by lobin21** [comment]
Testing again now :-)

**Comment by lobin21** [comment]
OK this now works! Great job! Thanks
